#!/bin/bash

#PBS -N PanelApp_ID_Download 
#PBS -r n
#PBS -l walltime=24:00:00
#PBS -l ncpus=2,mem=10Gb
#PBS -m ae
#PBS -M Alan.Robertson@qimrberghofer.edu.au 
#PBS -o /mnt/backedup/home/alanR/experiments/log/panelapp
#PBS -e /mnt/backedup/home/alanR/experiments/log/panelapp

#-------------------------------------
# 
# Script:	1-1 Download PanelApp IDs 
# Summary:	This script was designed to run the panelapp ID downloader tool 
# Created: 	2023-05-02
# 
#-------------------------------------

#-------------------------------------------
# Part 1: Enter your variables here
#------------------------------------------

#Name experiment
NAME="PANELAPP ID DOWNLOADER" 
#Define location of the script and the params file
SCRIPT="1-1_DownloadIDs.py"
#location
RAW_LOC="/mnt/backedup/home/alanR/ALAN_SCRIPTS/Vigenlint/PADA-WAN/1-1/GIT"
#Define parameters file
PARAM="1-1_params.txt"
#PARAM="1-1_downloadAU_params.txt"
#PARAM="1-1_downloadUK_params.txt"
#---------------------------------------------
echo "Experiment name: ${NAME}"  
echo "Parameter file: ${PARAM}"
echo ""

#Extract the version of PanelApp being used from the params file 
#echo "TESTING VERSION"
VERSION=$(less ${RAW_LOC}/${PARAM} | awk '/RUN/ {print $2}')
echo "Version = ${VERSION}"
echo""

#save additional information with logs
LOG_DIR="/mnt/backedup/home/alanR/experiments/log/panelapp"
timestamp=$(date "+%Y-%m-%d_%H-%M")
cp ${RAW_LOC}/${PARAM} ${LOG_DIR}/${timestamp}_${PARAM}

#Load Modules
module load python/3.9.13 
echo "Modules loaded:"
module list
echo ""

#Define proxy (ensure cluster can connect to websites outside of QIMR)
source ~/.proxy

#Define the  working directory
OUTPUT_DIR="/working/lab_nicw/alanR/PANELAPP/${VERSION}/ID"
mkdir -p ${OUTPUT_DIR}
echo "Moving to:"
cd ${OUTPUT_DIR}
pwd

#-------------------------------------------
# Part 2: Running the tool 
#------------------------------------------
echo "CONNECTION TO PANELAPP ${VERSION}"
python3  ${RAW_LOC}/${SCRIPT} --file-path ${RAW_LOC}/${PARAM} 
echo ""

echo "Files Produced:"
ls
