#!/bin/bash

#PBS -N PanelApp_CharacteriseChange 
#PBS -r n
#PBS -l walltime=2:00:00
#PBS -l ncpus=2,mem=10Gb
#PBS -m ae
#PBS -M Alan.Robertson@qimrberghofer.edu.au 
#PBS -o /mnt/backedup/home/alanR/experiments/log/panelapp
#PBS -e /mnt/backedup/home/alanR/experiments/log/panelapp

#-------------------------------------
# 
# Script:	2-1 Characterise Gene Changes from PanelApp Data
# Summary:	This script was designed to run a python script that ingests the results from PanelApp, and characterises how those panels have changed
# Created: 	2023-05-05
# 
#-------------------------------------

#-------------------------------------------
# Part 1: Enter variables here 
#------------------------------------------

#Name experiment
NAME="PANELAPP CHARACTERISE GENE CHANGES" 
#Define location of the script / param files
RAW_LOC="/mnt/backedup/home/alanR/ALAN_SCRIPTS/Vigenlint/PADA-WAN/2-1/GIT"
#Define script
SCRIPT="2-1_CharacteriseGeneChanges.py"
#Define parameters file
PARAM="2-1_params.txt"

echo "Experiment name: ${NAME}"  
echo "Parameter file: ${PARAM}"
echo ""

#Extract the version of PanelApp being used from the params file 
VERSION=$(less ${RAW_LOC}/${PARAM} | awk '/VER/ {print $2}')
OUT_DIR=$(less ${RAW_LOC}/${PARAM} | awk '/OUTPUTDIR/ {print $2}')
echo "Version = ${VERSION}"
echo "OUT-DIR = ${OUT_DIR}"
sleep 5
echo""

#save additional information with logs
LOG_DIR="/mnt/backedup/home/alanR/experiments/log/panelapp"
timestamp=$(date "+%Y-%m-%d_%H-%M")
cp ${RAW_LOC}/${PARAM} ${LOG_DIR}/${timestamp}_2-1_${PARAM}

#Load Modules
module load python/3.9.13 
echo "Modules loaded:"
module list
echo ""

#Define proxy (ensure cluster can connect to websites outside of QIMR)
#source ~/.proxy

#Define the  working directory
OUTPUT_DIR=${OUT_DIR}
mkdir -p ${OUTPUT_DIR}
echo "Moving to:"
cd ${OUTPUT_DIR}
pwd
#sleep 5

#-------------------------------------------
# Part 2: Running the tool 
#------------------------------------------
echo "DETERMINING GENE CHANGES"
python3  ${RAW_LOC}/${SCRIPT} --file-path ${RAW_LOC}/${PARAM} 
#echo ""

#echo "Files Produced:"
#ls
